name: Build and Deploy Node App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Node App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  # Adjust based on your project's requirement
      
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE  # Change directory to the repository root
          npm install
          

      - name: Run node application
        run: npm run server  # Ensure this script is configured correctly for deployment
